server:
  port: 8010

spring:
  kafka:
    bootstrap-servers: localhost:9092

app:
  topic:
    foo: mytest-topic

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.tnikhil: DEBUG
    
